language: php

php:
  - 5.4

env:
  - UN=deux

before_script:
  - chmod +x ./tests/travis.sh
  - ./tests/travis.sh 
  - wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
script: php mageekguy.atoum.phar -d tests/units

notifications:
  email:
    - jpasqualini75@gmail.com


